name: CI Checks

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4

      - name: Downloads
        run: go get -t ./...

      - name: Run tests
        run: go test ./...

  build:
    name: Build Application
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: Checkout out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Copy files
        run: |
          mkdir ./artifacts
          cp api ./artifacts

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts
